### PR TITLE
Fix aux tablet panic

### PR DESCRIPTION
**Pull request by peads**
Added device finalization functionality for the virtio input to allow the transition from Sys7 to A/UX to gracefully go down, and come back up without causing a full system freeze upon first pointer input once in the A/UX environment. _*N.B. The virtio input *does not* work once in A/UX, but if another pointing (e.g. adb-mouse) device is connected, A/UX will use it and the virtio device will be ignored.*_ 

Future work would be to regain the function of the virtio input after the transition.

### CODE REVIEW

**Comment by peads** [comment]
Interestingly, it appears to have no problems rebooting with Sys7.1/Sys7.0 (not inclusive of in A/UX mode, but that doesn't work right in qemu anyway), but it has issues rebooting in OS 8.1. Something to investigate, I suppose.

**Comment by elliotnunn** [comment]
Thanks for the patchset! It looks like we have three issues to address:

1. None of the drivers correctly shut down: this would mean freeing memory, undoing various “trap patches”, resetting the device and turning off interrupts (this last one is probably why A/UX is crashing). There is a very nasty bug that I haven’t yet fixed in the 68k driver assembly code that will cause memory corruption if a driver is opened a second time.
2. My C code is of fairly modest quality and does not agree with -Wall.
3. A true Unix driver will be needed for A/UX. I think SolraBizna is the person to talk to here.

Would you mind if I take some time to review your patches with a focus on (1) and commit that part? Then we turn our attention to code cleanup and an A/UX driver.

**Comment by peads** [comment]
Sure. I'm probably done at this point. It does what I need it to do; it allows me to start A/UX without panicking and have a mouse (albeit a relative pointing device), but also have an absolute pointing device when I'm not running A/UX. Honestly, after scouring the internet for the docs on driver dev for A/UX, I've found that they apparently haven't been preserved in any form, rendering further development beyond my meager hobbyist-interest.

**Comment by peads** [comment]
1. OK. I think it is still worthwhile to have the ability to finalize at least the pointing device here in the case that we want to switch to A/UX, such that it can fall back to the standard relative pointing device. Maybe I'm not seeing the corruption issue because I exclusively use qemu, but rebooting--when A/UX is not in the picture because rebooting doesn't work correctly in qemu anyway--works flawlessly. For example, my test setup has one disk image with Sys7 / A/UX and another disk with just OS8 attached. If I disable automatically starting A/UX by removing the alias from Startup Items, I can even use the Startup Disk control panel to switch between Sys7 and OS8 and it reboots flawlessly. It can even be rebooted ad nauseam, and the pointing device is continues to work without issues. Obviously, that's not truly a good QA of my patch, but it's a starting point. I think you're right however, I got a little carried-away with the commits got on this one. I'll squash them and re-submit the PR. 
2. Give yourself credit where it's due, you nailed creating a driver that absolutely obviated the one major annoyance I had while emulating the m68k. I just want to help improve it if I can. I didn't keep `-Wall` in there, but I noticed I left the `-Werror`. I'll revert that since it's largely a preference thing. That said, it does keep **my** mediocre C skills from biting me. 
3. Yeah, I think I started with an ambition to have it work all the way through the A/UX startup, but the pointing device is somewhat less important in that environment, at least for what I do, which is mostly keyboard-based anyhow. Maybe someday someone will find and digitize a copy of "A/UX Device Drivers Kit / Building A/UX Device Drivers" that I lamented not being available earlier. It's a new one for me: experiencing inverse scope creep.

**Comment by elliotnunn** [comment]
Patrick, I have significantly reworked the OS-driver glue code to enable clean driver unloading, and written cleanup functions to free memory and switch off interrupts. This should let A/UX load without a spurious interrupt error. Please try it out and let me know.

Unfortunately a rebooted plain Mac OS system still dies with a dsBadSlotInt error when the cursor is moved, because the shutdown process doesn't close drivers and we never get a chance to reset the virtio device. I should look further into this. Maybe the virtio devices should "know" that the computer has restarted.

**Pull request closed without merging**
